// Code generated by github.com/fdvky1/wabot-go DO NOT EDIT.
package command
import (
	"github.com/fdvky1/wabot-go/internal/handler"
	"github.com/zhangyunhao116/skipmap"
)
var Commands []*handler.Command
var StateMap *skipmap.StringMap[int]
func GetState(number string, types string) (int, bool) {
	return StateMap.Load(number + "-" + types)
}
func SetState(number string, types string, value int) {
	StateMap.Store(number+"-"+types, value)
}
func DelState(number string, types string) {
	StateMap.Delete(number + "-" + types)
}
func GenerateAllCommands() {
	StateMap = skipmap.NewString[int]()
	AddParticipantsCommand()
	AxisCommand()
	EveryoneCommand()
	HelpCommand()
	HiCommand()
	KickParticipantsCommand()
	StickerCommand()
}

func AddCommand(command *handler.Command) {
	Commands = append(Commands, command)
}
